//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanserMenuV3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanserMenuV3.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BROWSE {
            get {
                return ResourceManager.GetString("BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom File Name:.
        /// </summary>
        public static string CFN {
            get {
                return ResourceManager.GetString("CFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Modifiers.
        /// </summary>
        public static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Settings:.
        /// </summary>
        public static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursors:.
        /// </summary>
        public static string CUR {
            get {
                return ResourceManager.GetString("CUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DEBUG {
            get {
                return ResourceManager.GetString("DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time:.
        /// </summary>
        public static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LANG {
            get {
                return ResourceManager.GetString("LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps Found:.
        /// </summary>
        public static string MF {
            get {
                return ResourceManager.GetString("MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods:.
        /// </summary>
        public static string MOD {
            get {
                return ResourceManager.GetString("MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANSER Menu made with &lt;3 by Meloons#8078.
        /// </summary>
        public static string MSG {
            get {
                return ResourceManager.GetString("MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Database Check.
        /// </summary>
        public static string NDC {
            get {
                return ResourceManager.GetString("NDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update Check.
        /// </summary>
        public static string NUC {
            get {
                return ResourceManager.GetString("NUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a map.
        /// </summary>
        public static string PAM {
            get {
                return ResourceManager.GetString("PAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a mode:.
        /// </summary>
        public static string PAMD {
            get {
                return ResourceManager.GetString("PAMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch:.
        /// </summary>
        public static string PITCH {
            get {
                return ResourceManager.GetString("PITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string QS {
            get {
                return ResourceManager.GetString("QS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string REC {
            get {
                return ResourceManager.GetString("REC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Replay Path:.
        /// </summary>
        public static string RP {
            get {
                return ResourceManager.GetString("RP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Time:.
        /// </summary>
        public static string SCT {
            get {
                return ResourceManager.GetString("SCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a map:.
        /// </summary>
        public static string SFAM {
            get {
                return ResourceManager.GetString("SFAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin:.
        /// </summary>
        public static string SKIN {
            get {
                return ResourceManager.GetString("SKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SKIP {
            get {
                return ResourceManager.GetString("SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string SPEED {
            get {
                return ResourceManager.GetString("SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        public static string ST {
            get {
                return ResourceManager.GetString("ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Cursors:.
        /// </summary>
        public static string TAG {
            get {
                return ResourceManager.GetString("TAG", resourceCulture);
            }
        }
    }
}
